---
- name: NTP Configuration (EOS)
  arista.eos.eos_ntp_global:
    config: "{{ net_ntp }}"
    state: replaced
  notify: save eos config
  register: ntp_out

# dummy ACL due to https://github.com/ansible-collections/arista.eos/issues/334
- name: SNMP Configuration (EOS)
  vars:
    _acl:
      acl_v4: demo
  arista.eos.eos_snmp_server:
    config:
      communities: "{{ net_snmp.communities | map('combine', _acl) }}"
    state: replaced
  notify: save eos config
  register: snmp_out
