---
- name: Gather facts
  cisco.nxos.nxos_facts:
    gather_subset: min

- name: Purge local users
  cisco.nxos.nxos_user:
    purge: yes
  notify: save cisco.nxos.nxos config
  register: user_out

# NX-OS requires that you specify a VRF for NTP
# This deviates from the other platforms, so we modify the data here
- name: Update NTP Configuration
  vars:
    _vrf:
      vrf: "{{ net_ntp_vrf }}"
  ansible.builtin.set_fact:
    net_ntp:
      servers: "{{ net_ntp.servers | map('combine', _vrf) }}"
