---
- name: Gather facts
  junipernetworks.junos.junos_facts:
    gather_subset: min

- name: Purge local users
  junipernetworks.junos.junos_user:
    name: admin
    purge: yes
  register: user_out
