---
- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_network_os }}.yml"

- name: Set ticketing flag
  ansible.builtin.set_fact:
    net_needs_change: yes
  when: >-
    ntp_out.changed or
    snmp_out.changed

- name: Set table variables if requested
  ansible.builtin.include_tasks: table.yml
  when: net_set_table

- name: Determine commands
  vars:
    _new: "{{ item.commands }}"
  ansible.builtin.set_fact:
    net_all_commands: "{{ net_all_commands | default([]) + _new }}"
  loop:
    - "{{ ntp_out }}"
    - "{{ snmp_out }}"
  when: net_needs_change | default(false)
