---
- name: save cisco.nxos.nxos config
  cisco.nxos.nxos_config:
    save_when: always
  when: not ansible_check_mode

- name: save arista.eos.eos config
  arista.eos.eos_config:
    save_when: always
  when: not ansible_check_mode

- name: save junipernetworks.junos.junos config
  ansible.builtin.debug:
    msg: Not applicable
  when: not ansible_check_mode
